CHROME = "Chrome"
CHROMIUM = "Chromium"
EDGE = "Edge"
FIREFOX = "Firefox"
DEFAULT_BROWSER =CHROME
SUPPORTED_BROWSERS = [CHROME, FIREFOX, EDGE, CHROMIUM]


REDDIT_BASE_URL = "https://www.reddit.com"


SCROLL_DISTANCE = 500
SLEEP_MIN_SECONDS = 0
SLEEP_MAX_SECONDS = 4


GEMINI_MODEL = "gemini-2.0-flash"

INDENT_SIZE = 4

OUTPUT_DIRECTORY = "./persona"